# Generated by Django 4.2.30 on 2026-09-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0054_merge_20260902_1224"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlconfigaiinspect",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="mysqlconfigaiinspect",
            name="msg",
            field=models.TextField(default="", help_text="备注信息"),
        ),
        migrations.AddField(
            model_name="mysqlconfigaiinspect",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
    ]
