# Generated by Django 4.2.30 on 2026-07-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbm_aiagent", "0004_mcpcalleeplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselinedisk",
            name="disk_name",
            field=models.CharField(
                help_text="唯一名称约定为 disk_type 与 capacity_gb 的下划线拼接：disk_type 为 DiskType 枚举取值，capacity_gb 为单盘容量整数 GB，形如 NVME_SSD_3570",
                max_length=128,
                unique=True,
                verbose_name="磁盘配置名称",
            ),
        ),
        migrations.AlterField(
            model_name="baselinedisk",
            name="is_local",
            field=models.BooleanField(default=False, help_text="指示磁盘是否为本地盘, 默认否; IT 开头机型为本地盘", verbose_name="是否本地盘"),
        ),
    ]
