# Generated by Django 3.2.25 on 2025-06-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0002_alter_dbperiodictask_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MySQLBackupRollbackTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, verbose_name="演练业务ID")),
                ("cluster_id", models.IntegerField(default=0, verbose_name="备份来源集群ID")),
                ("cluster_domain", models.CharField(default="", max_length=255, verbose_name="备份来源域名")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("tendbsingle", "MySQL单节点集群"),
                            ("tendbha", "MySQL高可用集群"),
                            ("tendbcluster", "TendbCluster集群"),
                            ("tbinlogdumper", "TBinlogDumper"),
                            ("redis", "Redis"),
                            ("PredixyRedisCluster", "RedisCluster集群"),
                            ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                            ("TwemproxyRedisInstance", "TendisCache集群"),
                            ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                            ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                            ("RedisInstance", "RedisCache主从版"),
                            ("TendisSSDInstance", "TendisSSD主从版"),
                            ("TendisplusInstance", "Tendisplus主从版"),
                            ("RedisCluster", "RedisCluster集群"),
                            ("TendisplusCluster", "TendisplusCluster集群"),
                            ("TendisplusInstance", "Tendisplus存储版集群"),
                            ("RedisInstance", "TendisCache集群"),
                            ("TendisSSDInstance", "TendisSSD集群"),
                            ("es", "ES集群"),
                            ("kafka", "Kafka集群"),
                            ("hdfs", "Hdfs集群"),
                            ("influxdb", "Influxdb实例"),
                            ("pulsar", "Pulsar集群"),
                            ("doris", "Doris集群"),
                            ("vm", "vm集群"),
                            ("dbmon", "redis监控"),
                            ("MongoReplicaSet", "Mongo副本集"),
                            ("MongoShardedCluster", "Mongo分片集群"),
                            ("riak", "Riak集群"),
                            ("sqlserver_single", "sqlserver单节点版"),
                            ("sqlserver_ha", "sqlserver主从版"),
                            ("oracle_primary_standby", "oracle主从版"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("backup_id", models.CharField(default="", max_length=255, verbose_name="备份ID")),
                ("backup_begin_time", models.DateTimeField(default=None, verbose_name="备份开始时间")),
                ("backup_end_time", models.DateTimeField(default=None, verbose_name="备份结束时间")),
                ("backup_total_size", models.IntegerField(default=0, verbose_name="备份总大小")),
                ("backup_type", models.CharField(default="", max_length=32, verbose_name="备份类型")),
                ("backup_tool", models.CharField(default="", max_length=32, verbose_name="备份工具")),
                ("time_zone", models.CharField(default="", max_length=32, verbose_name="时区")),
                ("task_id", models.IntegerField(default=0, verbose_name="关联的任务ID")),
                ("task_status", models.CharField(default="", max_length=32, verbose_name="任务状态")),
                ("task_info", models.TextField(default="", verbose_name="任务信息")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
